### ISSUE TITLE
Integrate with persist middleware

### ISSUE THREAD

**Issue by PencilCoder0E** [Romainlg29/use-broadcast#1]
As of now there's no way to wrap this middleware with another middleware.
I was wondering if there's a solution for this.

Thanks for your work!

![image](https://github.com/Romainlg29/use-broadcast/assets/139707733/f3a39d04-90aa-4862-b0b0-11730c9323ad)

FYI: Ramda pipe didn't work

**Comment by Romainlg29** [comment]
Hi,

You missed the shared config object.

```ts
export const useMyStore = create<MyStoreState>(
  shared(
    persist(
      (set, get) => ({
        count: 0,
        increment: () => set((state) => ({ count: state.count + 1 })),
      }),
      { name: "auth-storage" }
    ),
    { name: "auth-store" }
  )
);
```

shared takes a mandatory options object with a name, it's used by the broadcast channel to communicate.

**Comment by PencilCoder0E** [comment]
> Hi,
> 
> You missed the shared config object.
> 
> ```ts
> export const useMyStore = create<MyStoreState>(
>   shared(
>     persist(
>       (set, get) => ({
>         count: 0,
>         increment: () => set((state) => ({ count: state.count + 1 })),
>       }),
>       { name: "auth-storage" }
>     ),
>     { name: "auth-store" }
>   )
> );
> ```
> 
> shared takes a mandatory options object with a name, it's used by the broadcast channel to communicate.

Thank you so much!
I thought about doing this earlier but I was thinking it might not work. Haha, I should have tried. But thank you very much, once again.

It works now.
