### ISSUE TITLE
Allow execution in context without 'window'

### ISSUE THREAD

**Issue by tomasmenezes** [Romainlg29/use-broadcast#13]
Instances such as service workers, that support BroadcastChannel, but where `window` is not defined, should be supported. This is currently prevented in the shared implementation by the two window references:

```typescript
if (typeof window === 'undefined') {
    console.warn('BroadcastChannel is not supported in this environment. The store will not be shared.');
    return f(set, get, store);
}
```
```typescript 
window.addEventListener('beforeunload', onClose);
```

**Comment by Romainlg29** [comment]
Hi @tomasmenezes ,
I may have a fix for this, can you share a small example code to test on ?

**Comment by tomasmenezes** [comment]
Hi @Romainlg29, sorry for the lack of feedback or code example - haven't really had any time at all to produce either.
The fix works perfectly on my end. I had just bypassed both window checks locally but didn't know if there were any side-effects.

**Comment by Romainlg29** [comment]
> Hi @Romainlg29, sorry for the lack of feedback or code example - haven't really had any time at all to produce either. The fix works perfectly on my end. I had just bypassed both window checks locally but didn't know if there were any side-effects.

Ok, thank you for replying.
I'll merge it.
