### ISSUE TITLE
ReferenceError: window is not defined with zustand

### ISSUE THREAD

**Issue by janith-bl** [Romainlg29/use-broadcast#4]
**Describe the bug**
I am using with zustand and getting an error during the compilation. But functionality is working properly.
⨯ node_modules/use-broadcast-ts/dist/index.mjs (387:2) @ window
⨯ ReferenceError: window is not defined

**To Reproduce**
1. Use 'shared' with zustand
2. See the terminal during the running

**Expected behavior**
Without runtime errors

**Screenshots**

<img width="637" alt="image" src="https://github.com/Romainlg29/use-broadcast/assets/157475855/44ffbc42-e8f1-4524-910d-9f27a79c1229">

**Comment by Romainlg29** [comment]
> **Describe the bug** I am using with zustand and getting an error during the compilation. But functionality is working properly. ⨯ node_modules/use-broadcast-ts/dist/index.mjs (387:2) @ window ⨯ ReferenceError: window is not defined
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use 'shared' with zustand
> 2. See the terminal during the running
> 
> **Expected behavior** Without runtime errors
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/157475855/325227047-44ffbc42-e8f1-4524-910d-9f27a79c1229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNjkyMTAsIm5iZiI6MTcxNDA2ODkxMCwicGF0aCI6Ii8xNTc0NzU4NTUvMzI1MjI3MDQ3LTQ0ZmZiYzQyLWU4ZjEtNDUyNC05MTBkLTlmMjdhNzljMTIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQxODE1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGE0NTJiZjAwYmZjNjFiZGIwOTM1ZjA0NjdlMGI2NWMzNzY4ZDZlZWE1ZTZiM2FmNzc0YTJjZGViOTQ4ODkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ml4SHINDbH-8_Sr36fo8pOP1A5V-RVAA0DX5rKBkui8">

Hi,
What version of use-broadcast-ts are you using?

**Comment by Romainlg29** [comment]
I found the issue, I will try to push a fix tomorrow.
You can still use it inside your clients components.

**Comment by Romainlg29** [comment]
> **Describe the bug** I am using with zustand and getting an error during the compilation. But functionality is working properly. ⨯ node_modules/use-broadcast-ts/dist/index.mjs (387:2) @ window ⨯ ReferenceError: window is not defined
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use 'shared' with zustand
> 2. See the terminal during the running
> 
> **Expected behavior** Without runtime errors
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/157475855/325227047-44ffbc42-e8f1-4524-910d-9f27a79c1229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzk3MjQsIm5iZiI6MTcxNDEzOTQyNCwicGF0aCI6Ii8xNTc0NzU4NTUvMzI1MjI3MDQ3LTQ0ZmZiYzQyLWU4ZjEtNDUyNC05MTBkLTlmMjdhNzljMTIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMzUwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MThlY2MxODlmOTQxZDY0MGEwZTk1YTkzNzQ0M2RiNTU2ODEwMTQ4NWJjODI5MjUxN2U3ZjYwMmVhNjFjMDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FJ-FdIhnQMe01bWyxlbh4lj71T7sZ-R_ehU8bCZLkkI">

Hi @janith-bl ,

It has been fixed in the 1.4.5 version.
However, the intended usage of it is to be used in a client component as the server environment doesn't support the Broadcast Channel API.

Let me know if it's right for you.
