### ISSUE TITLE
Demo site incorrect

### ISSUE THREAD

**Issue by reintroducing** [Romainlg29/use-broadcast#6]
This is a really cool implementation, and I really like the zustand implementation as well. Just as an FYI, on your demo site, line 14 of the code in the UI says `decrement` but it should say `increment` :)

**Comment by Romainlg29** [comment]
> This is a really cool implementation, and I really like the zustand implementation as well. Just as an FYI, on your demo site, line 14 of the code in the UI says `decrement` but it should say `increment` :)

Thank you!
I'll fix it.

**Comment by Romainlg29** [comment]
It's now fixed!
