### ISSUE TITLE
possible to read `isMain` ? 

### ISSUE THREAD

**Issue by samburgers** [Romainlg29/use-broadcast#8]
Hi, im wondering if its possible to read the `isMain` value across tabs? Use case is so i can have a shared `isPlaying` state, but only take actions on only one of the tabs (play/pause the audio ref for example). Thanks!

**Comment by Romainlg29** [comment]
Hi @samburgers ,

I'm looking at it. However, it can take a few days, because I'm struggling with the types...

**Comment by samburgers** [comment]
Thank you!

**Comment by Romainlg29** [comment]
Hi @samburgers ,

I have added a new `onBecomeMain` callback function available in the options.
By using the callback, you can update states or anything else for your use case.

In a near future, maybe for Zustand v5, I'll try to implement another way of doing that.
I have encountered an issue, that I think comes from my bundling...

Let me know if you have other queries!
